import test from 'node:test';import assert from 'node:assert/strict';
import {freshState,reduce,decide,newQuote,snapshot,emailEligibility,priceFor} from '../src/demo/model.js';
const hotel={id:'test',name:'Test',price:500};
function ready(){return {...freshState(),email_permission:true,experiment:'treatment'}}
test('quote recovery respects time, expiry, purchase and cancellation',()=>{let s=ready();const q=newQuote(hotel,{adults:2,children:0,start:'2027-10-20'},s);s=reduce(s,'checkout',{quote:q});assert.equal(decide(s).key,'waiting');s=reduce(s,'advance',{hours:1});assert.equal(decide(s).key,'recovery');s=reduce(s,'advance',{hours:48});assert.equal(decide(s).key,'expired');s=reduce(s,'purchase',{booking:{...q,id:'booking'}});assert.equal(decide(s).key,'service');s=reduce(s,'cancel');assert.equal(decide(s).key,'cancelled');assert.equal(snapshot(s).net_value,0)});
test('marketing consent and control arm suppress marketing, not care',()=>{let s={...ready(),history_count:6};assert.equal(decide(s).key,'vip');assert.equal(decide({...s,email_permission:false}).key,'generic');assert.equal(decide({...s,experiment:'control'}).key,'control');assert.equal(decide({...s,complaint:true,experiment:'control'}).key,'care')});
test('price watch requires active explicit permission and unexpired offer',()=>{const s={...ready(),email_permission:false,watch:{active:true,permission:true,current_price:900,threshold:1000,expires_at:'2099-01-01'}};assert.equal(decide(s).key,'price');assert.equal(decide({...s,watch:{...s.watch,permission:false}}).key,'generic');assert.equal(decide({...s,watch:{...s.watch,expires_at:'2020-01-01'}}).key,'generic')});
test('owned extra suppresses upsell; service case has priority',()=>{let s=ready();s.booking={id:'book',start:new Date(new Date(s.clock).getTime()+7*86400000).toISOString()};s.stage='booked';assert.equal(decide(s).key,'pretrip');s=reduce(s,'extra',{extra:'transfer'});assert.equal(decide(s).key,'service');assert.equal(decide({...s,complaint:true}).key,'care')});
test('preview frequency cap and step deduplication',()=>{let s={...ready(),history_count:6};const d=decide(s),elig=emailEligibility(s,d);assert.equal(elig.allowed,true);s=reduce(s,'contact',{key:elig.key,marketing:true});assert.equal(emailEligibility(s,d).allowed,false);assert.equal(emailEligibility(s,{key:'winback',marketing:true}).allowed,false);s=reduce(s,'advance',{hours:24});assert.equal(emailEligibility(s,{key:'winback',marketing:true}).allowed,true)});
test('package price includes chosen meal plan, room and travelers',()=>{assert.equal(priceFor(hotel,{board:'All Inclusive',room:'Doppelzimmer Superior',adults:2,children:1}),1873.55)});
