export const asset = (name) => `/assets/${name}`;
export const destinations = [
  "Mallorca",
  "Griechenland",
  "Türkei",
  "Ägypten",
  "Malediven",
  "Dominikanische Republik",
];
export const hotels = [
  {
    id: "calimera-fido-gardens",
    name: "Calimera Fido Gardens",
    town: "Cala d’Or",
    destination: "Mallorca",
    price: 544,
    rating: 93,
    reviews: 3631,
    stars: 3,
    image: "c810b375c1762f9b.webp",
    gallery: [
      "c810b375c1762f9b.webp",
      "dcd7e417725a0a45.webp",
      "47edb74394f4618c.webp",
    ],
    amenities: ["Familienfreundlich", "Pool", "WLAN", "Animation"],
    family: true,
  },
  {
    id: "sentido-fido-punta-del-mar",
    name: "Sentido Fido Punta del Mar",
    town: "Costa de la Calma",
    destination: "Mallorca",
    price: 530,
    rating: 97,
    reviews: 2198,
    stars: 4,
    image: "12ff4009052688dd.webp",
    gallery: ["12ff4009052688dd.webp", "adbe9c6d8cbf2b63.webp"],
    amenities: ["Adults only", "Wellness", "Pool", "Meerblick"],
    family: false,
  },
  {
    id: "bahia-suites-camp-de-mar",
    name: "Bahía Suites Camp de Mar",
    town: "Camp de Mar",
    destination: "Mallorca",
    price: 542,
    rating: 98,
    reviews: 869,
    stars: 4,
    image: "e28ca4f2d53a539b.webp",
    gallery: ["e28ca4f2d53a539b.webp", "47edb74394f4618c.webp"],
    amenities: ["Strandnähe", "Pool", "WLAN", "Wellness"],
    family: true,
  },
  {
    id: "ses-fotges",
    name: "Ses Fotges",
    town: "Platja de Muro",
    destination: "Mallorca",
    price: 547,
    rating: 92,
    reviews: 464,
    stars: 4,
    image: "47edb74394f4618c.webp",
    gallery: ["47edb74394f4618c.webp"],
    amenities: ["Familienfreundlich", "Strandnähe", "Pool", "WLAN"],
    family: true,
  },
  {
    id: "las-gaviotas-suites",
    name: "Las Gaviotas Suites",
    town: "Platja de Muro",
    destination: "Mallorca",
    price: 686,
    rating: 86,
    reviews: 1077,
    stars: 4,
    image: "adbe9c6d8cbf2b63.webp",
    gallery: ["adbe9c6d8cbf2b63.webp", "12ff4009052688dd.webp"],
    amenities: ["Wellness", "Pool", "WLAN", "Fitness"],
    family: false,
  },
];
export const collections = [
  {
    title: "Last Minute in den Urlaub",
    cards: [
      [
        "Last Minute",
        "Die Sonne wartet auf dich",
        "fba4ae189d6a0ff9.webp",
        "Mallorca",
        "Bis zu 50 % sparen",
      ],
      [
        "Ägypten",
        "Sonne satt am Roten Meer",
        "ec754c2436112eab.webp",
        "Ägypten",
        "Top-Angebote",
      ],
      [
        "Tunesien",
        "Dein Platz am Meer",
        "2d6c3542e331e66b.webp",
        "Mallorca",
        "Jetzt entdecken",
      ],
      [
        "Kreta",
        "Griechisches Urlaubsglück",
        "3d4604b485a11192.webp",
        "Griechenland",
        "Last Minute",
      ],
    ],
  },
  {
    title: "Aktuelle Tipps und Themen für deinen Urlaub",
    cards: [
      [
        "Macht Urlaub",
        "Jetzt bis zu 40 % sparen²",
        "b2837364fbc1fb20.webp",
        "Mallorca",
        "Frühbucher",
      ],
      [
        "Fernweh? Ab ans Meer!",
        "Traumstrände entdecken",
        "6b87355b2447f962.webp",
        "Malediven",
        "Sonne tanken",
      ],
      [
        "Mit Emirates um die Welt",
        "Entspannt in den Urlaub",
        "90e39442cd107750.webp",
        "Malediven",
        "Flug & Hotel",
      ],
      [
        "Winterurlaub",
        "Vorfreude auf den Schnee",
        "04f3dd092d6d729b.webp",
        "Mallorca",
        "Winter 2026/27",
      ],
    ],
  },
  {
    title: "Frühbucherangebote 2027: Jetzt bis zu 40 % sparen!²",
    cards: [
      [
        "Sommer 2027",
        "Der frühe Vogel macht Urlaub",
        "1c915d9f29ccded2.webp",
        "Mallorca",
        "Früh buchen & sparen",
      ],
      [
        "Griechenland",
        "Inselglück in Blau und Weiß",
        "47c7f3a7694a4bd6.webp",
        "Griechenland",
        "Bis zu 40 %",
      ],
      [
        "Ägypten",
        "Dein Sommer beginnt hier",
        "a8dc7756d363507f.webp",
        "Ägypten",
        "Bis zu 40 %",
      ],
      [
        "Türkei",
        "Sonne, Strand und Meer",
        "935c3d4659341fb3.webp",
        "Türkei",
        "Bis zu 40 %",
      ],
    ],
  },
];
export const brands = [
  ["Sentido", "730c9ea29adcd91e.webp"],
  ["Aldiana", "2438e860a6db48ec.webp"],
  ["Playitas", "a7e5fbf384e36f94.webp"],
  ["Calimera", "bdeee8349b5f206b.webp"],
  ["ananea", "6b310133155eb5f7.webp"],
  ["aja", "c06e865419d6403d.webp"],
  ["A-ROSA", "52f4d8dcf200c84c.webp"],
  ["HENRI", "3a60fa06dd1d3556.webp"],
  ["MIRA", "e31da3d7865ad29d.webp"],
  ["SEETELHOTELS", "d87f9f5ead6a9451.webp"],
];
// Illustrative destination-specific inventory beyond the captured Mallorca hotels.
const destinationExamples = [
  [
    "Griechenland",
    "Griechenland",
    "Kreta",
    "Aegean Beach Resort",
    "3d4604b485a11192.webp",
    629,
  ],
  [
    "Türkei",
    "Türkei",
    "Ölüdeniz",
    "Lykia Coast Resort",
    "935c3d4659341fb3.webp",
    589,
  ],
  [
    "Ägypten",
    "Ägypten",
    "Hurghada",
    "Red Sea Garden Resort",
    "ec754c2436112eab.webp",
    649,
  ],
  [
    "Malediven",
    "Malediven",
    "Nord-Malé-Atoll",
    "Island Lagoon Resort",
    "f3afb69022ed2947.webp",
    1489,
  ],
  [
    "Dominikanische Republik",
    "Dominikanische Republik",
    "Punta Cana",
    "Caribe Palm Resort",
    "6b87355b2447f962.webp",
    1199,
  ],
];
for (const [
  destination,
  country,
  town,
  name,
  image,
  price,
] of destinationExamples) {
  hotels.push({
    id: name.toLowerCase().replaceAll(" ", "-"),
    name: `${name} (Demo)`,
    town,
    country,
    destination,
    price,
    rating: 95,
    reviews: 248,
    stars: 4,
    image,
    gallery: [image],
    amenities: ["Strandnähe", "Pool", "WLAN", "Familienfreundlich"],
    family: true,
  });
}
